### PR TITLE
added support for us english language

### PR DESCRIPTION
**Pull request by hakonn**

### CODE REVIEW

**Comment by hakonn** [comment]
Hi @lonnkvist and @tholee, thank you for making this elastic nuget for episerver. It will save us a lot of time. 

May I ask, is it possible to speed up this very small pull request? We are unable to use the nuget since the language we use in episerver is not supported.

**Comment by tholee** [comment]
Hi @hakonn 

Yes, we will handle this pull request as soon as possible. As we speak we are currently changing the infrastructure for building and deploying this nuget, from personalized account to service account.  Please have a little patience. You can always pack it yourself.

**Comment by otanum** [comment]
@hakonn please validate 11.7.1.94-pre. Should be available in a couple of minutes.

**Review by tholee — APPROVED** [review]

**Comment by hakonn** [comment]
@otanum @tholee It works. No exceptions related to us english. Thanks guys! :)

**Comment by otanum** [comment]
PR included in v11.7.1.98

**Pull request merged**
